cssfrankfurt/cssfrankfurt.de

package-lock.json, package.json, src/App.vue, src/components/about/AboutFrank.vue, src/components/about/AboutOrganisers.vue, src/main.js
Decided to switch to FontAwesome as some icons that we wanted were missing.
=> From Feather Icons to FontAwesome

README.md
Replaced the badges with dynamic ones
=> Dynamic Badges

package.json, src/components/about/AboutOrganisers.vue
With the --fix option, the linter (and thus Travis) can automatically fix minor issues like trailing spaces
=> add auto-fixing to linter

src/components/events/EventList.vue, src/components/home/NewsFeed.vue, src/main.js
Added icons that weren't included in the last icon fix.
=> Added missing icons

src/components/about/AboutOrganisers.vue
- [] Enhancement (new feature/minor improvement)
Steffens quoty quote
=> Quoty quote

src/4_components/TheFooter.vue, src/App.vue
Fixed footer not being fixed to the bottom.
=> Added Fixed Footer

.github/CODE_OF_CONDUCT.md, .github/REPORTING_GUIDELINE.md
Thank you for submitting a pull request! Please provide us with enough details to make it easier for others to review your pull request:
Added Code of Conduct and a Reporting Guideline for reporting CoC violations.
=> added Code of Conduct and Reporting Guideline

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, package.json
Thank you for submitting a pull request! Please provide us with enough details to make it easier for others to review your pull request:
Updated documentation
Please include any comments that you might have
=> Updated documentation

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/REPORTING_GUIDELINES.md, README.md, package.json
Added code of conduct and reporting guideline
=> Code of Conduct, Reporting Guideline

docs/events/locations.md, docs/events/past.md, docs/events/upcoming.md
Added location info, fixes #41
=> Added location info

docs/README.md, docs/community/community.md, docs/events/upcoming.md
=> Fixed broken links

docs/de/README.md, docs/de/events/past.md, docs/de/events/upcoming.md, docs/events/past.md, docs/events/upcoming.md
- Added German README.md
- Added German page for upcoming events
- Added German page for past events
- Fixed a typo in upcoming and past events (English)
I'd appreciate any feedback! I'll keep going with more later :)
=> German README, upcming and past events

docs/.vuepress/config.js, docs/about/sponsors.md, docs/de/about/sponsors.md, docs/de/community/frankconf.md, docs/de/events/past.md, docs/de/events/upcoming.md
- Updated English and German sponsor space
- Removed FrankConf
- German version: removed emojis in front of events to reflect the English version
- Improved the overview of sponsor page and how to contribute
=> feat: updated content

README.md
Changed a link in README.md resulting in a 404 error.
=> fixed a 404 error in README.md

docs/de/events/conferences.md
Adds translation for conference section in german version of page.
=> Add german translation of conferences.md

docs/de/events/past.md, docs/de/events/upcoming.md, docs/events/past.md, docs/events/upcoming.md
update upcoming and past events
move Hacktoberfest from upcoming to past events
=> move Hacktoberfest to past events

docs/.vuepress/config.js, docs/de/legal/imprint.md, docs/de/legal/privacypolicy.md, docs/legal/imprint.md, docs/legal/privacypolicy.md
Added impressum and privacy policy, fixes #46
=> Added impressum and privacy policy

docs/de/about/coc.md, docs/de/about/mission.md
-added translation for "Our Mission"
-added translation for "Code of Conduct" #1 (#2 to #10 is still in english)
=> Add german translations

docs/.vuepress/config.js, docs/about/coc.md, docs/de/about/coc.md, docs/de/about/sponsors.md, docs/de/legal/privacypolicy.md
- remove broken link in coc pages
- fix and add missing sponsor logos in de
- fix config for legal pages in de
=> minor fixes in german pages

docs/de/events/past.md, docs/de/events/upcoming.md, docs/events/past.md, docs/events/upcoming.md
update list of upcoming and past events after tonights meetup
=> move grid in detail to past events

docs/about/team.md
- Fixes the broken link for dbsystel on the team page
- The link doesn't seem to work without the "www"
=> Fixed broken dbsystel link
